apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "otus-homework.fullname" . }}
  labels: 
    {{- include "otus-homework.labels" . | nindent 4 }}
data:
  postgres_user: {{ .Values.postgresql.postgresqlUsername }}
  postgres_db: {{ .Values.postgresql.postgresqlDatabase }}
  postgres_host: {{ .Release.Name }}-postgresql
  postgres_port: "{{ .Values.postgresql.service.port }}"

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "otus-homework.fullname" . }}
  labels:
    {{- include "otus-homework.labels" . | nindent 4 }}
type: Opaque
data:
  postgres_password: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}

