apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "otus-homework.fullname" . }}-migration"
  labels:
    {{- include "otus-homework.labels" . | nindent 4 }}
data:
  postgres_user: {{ .Values.postgresql.postgresqlUsername }}
  postgres_db: {{ .Values.postgresql.postgresqlDatabase}}
  postgres_host: {{ .Release.Name }}-postgresql
  postgres_port: "{{ .Values.postgresql.service.port}}"
  migration_code: |
    CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
      "MigrationId" character varying(150) NOT NULL,
      "ProductVersion" character varying(32) NOT NULL,
      CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
    );

    DO $$
    BEGIN
        IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200724163237_Initial') THEN
        CREATE TABLE "Users" (
            "Id" uuid NOT NULL,
            "Name" text NULL,
            "Email" text NULL,
            CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
        );
        END IF;
    END $$;

    DO $$
    BEGIN
        IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200724163237_Initial') THEN
        INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
        VALUES ('20200724163237_Initial', '3.1.6');
        END IF;
    END $$;

---

apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "otus-homework.fullname" . }}-migration"
  labels:
    {{- include "otus-homework.labels" . | nindent 4 }}
type: Opaque
data:
  postgres_password: {{ .Values.postgresql.postgresqlPassword | b64enc }}
