apiVersion: v1
kind: Service
metadata:
  name: {{ include "otus-homework.fullname" . }}
  labels:
    {{- include "otus-homework.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "otus-homework.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: web
  type: {{ .Values.service.type }}
