replicaCount: 3

# nameOverride: ""
# fullnameOverride: ""

service:
  type: NodePort
  port: 9000

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: arch.homework
      paths:
        - /otusapp/pavel-flyagin($|/)(.*)

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

postgresql:
  postgresqlPostgresPassword: pswd
  postgresqlUsername: otus-homework-api
  postgresqlPassword: myapppswd
  postgresqlDatabase: Otus-Homework

  service:
    type: NodePort
    port: 5432

  persistence: {}
    # enabled: true
    # size: 200Mi

  resources: {}
    # requests:
    #   memory: 256Mi
    #   cpu: 250m

